### ISSUE TITLE
That is not what i want

### ISSUE THREAD

**Issue by qizhongjian** [maincarry/R-Precision#1]

**Comment by qizhongjian** [comment]
The result doesn't match  one in paper.

**Comment by maincarry** [comment]
I got 62% for the R-Precision score on the pre-trained AttnGAN model, which is close to the result in the paper. The evaluation procedure is the same as the paper, and the only difference is that it uses the evaluated images from the model checkpoint and thus covers all captions in the dataset, rather than 30000 randomly sampled captions. Can you describe your result more specifically?

**Comment by huqiyii** [comment]
i have try to write the RP score ， and i got 62% too.   so i think he is write if we  use the algorithm in the paper
